### PR TITLE
Fix Service Header to use upper case value

### LINKED ISSUE #1528: Service header inconsistently case sensitive
### IoT Agent Node Lib version the issue has been seen with

3.3.0

### Bound or port used (API interaction)

Northbound (Provision API and NGSI Interactions)

### NGSI version

NGSIv2

### Are you running a container?

Yes, I am using a contaner (Docker, Kubernetes...)

### Image type

normal

### Expected behaviour you didn't see

That the fiwareservice header (or better everthing) is consistently case-sensitive or case-insensitive.

### Unexpected behaviour you saw

When creating a service group with the header:

> fiwareservice: Test
> fiware-servicepath: /Test

a service group is created as follows

```json
{
  "service": "test",
  "subservice": "/Test",
}
```
Now you can use this header

> fiwareservice: Test
> fiware-servicepath: /Test

To list and read the create service group, but not to delete or update the service group.

### Steps to reproduce the problem

```sh
curl --location 'http://localhost:4061/iot/services' \
--header 'fiware-service: Test' \
--header 'fiware-servicepath: /Test' \
--header 'Content-Type: application/json' \
--data '{
    "services": [
        {
            "apikey": "5a7ba897-61a6-43de-94b4-e0d91b261870",
            "cbroker": "http://orion:1026",
            "entity_type": "House",
            "resource": "",
            "type": "House",
            "autoprovision": "true"
        }
    ]
}'

curl --location 'http://localhost:4061/iot/services' \
--header 'fiware-service: Test' \
--header 'fiware-servicepath: /Test' \
--data ''
```
Response:
```json
{
    "count": 1,
    "services": [
        {
            "commands": [],
            "lazy": [],
            "attributes": [],
            "_id": "6555fb29563294ae401de5e4",
            "resource": "",
            "apikey": "5a7ba897-61a6-43de-94b4-e0d91b261870",
            "service": "test",
            "subservice": "/Test",
            "autoprovision": true,
            "__v": 0,
            "static_attributes": [],
            "internal_attributes": [],
            "entity_type": "House"
        }
    ]
}
```
```sh
curl --location --request DELETE 'http://localhost:4061/iot/services/?resource=&apikey=5a7ba897-61a6-43de-94b4-e0d91b261870' \
--header 'fiware-service: Test' \
--header 'fiware-servicepath: /Test' \
--data ''
```

Response of the last curl:
```json
{
    "name": "MISMATCHED_SERVICE",
    "message": "The declared service didn't match the stored one in the entity"
}
```

### Configs

```yaml
environment:
    - "IOTA_CB_HOST=orion"
    - "IOTA_CB_PORT=1026"
    - "IOTA_NORTH_PORT=4061"
    - "IOTA_REGISTRY_TYPE=mongodb"
    - "IOTA_MONGO_HOST=mongodb"
    - "IOTA_MONGO_PORT=27017"
    - "IOTA_MONGO_DB=iotagent-ul"
    - "IOTA_PROVIDER_URL=http://iot-agent:4061"
    - "IOTA_AUTOCAST=true"
    - "IOTA_MQTT_HOST=mosquitto"
    - "IOTA_MQTT_PORT=1883"
```

### Log output

```sh
time=2023-11-16T11:23:09.829Z | lvl=DEBUG | corr=661f3e7e-7798-4805-9c07-9f996f3955c1 | trans=661f3e7e-7798-4805-9c07-9f996f3955c1 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=Test | subsrv=/Test | msg=Body:
2023-11-16 12:23:09 
2023-11-16 12:23:09 {
2023-11-16 12:23:09     "defaultEntityNameConjunction": ":"
2023-11-16 12:23:09 }
2023-11-16 12:23:09 
2023-11-16 12:23:09  | comp=IoTAgent
2023-11-16 12:23:09 time=2023-11-16T11:23:09.830Z | lvl=DEBUG | corr=661f3e7e-7798-4805-9c07-9f996f3955c1 | trans=661f3e7e-7798-4805-9c07-9f996f3955c1 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["resource","apikey"] with queryObj {"apikey":"5a7ba897-61a6-43de-94b4-e0d91b261870"} | comp=IoTAgent
2023-11-16 12:23:09 time=2023-11-16T11:23:09.845Z | lvl=DEBUG | corr=1837960c-18c0-4096-b814-3673f25cab12 | trans=1837960c-18c0-4096-b814-3673f25cab12 | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=test | subsrv=/Test | msg=Device group data found: {"_id":"6555fb29563294ae401de5e4","resource":"","apikey":"5a7ba897-61a6-43de-94b4-e0d91b261870","type":"House","service":"test","subservice":"/Test","autoprovision":true} | comp=IoTAgent
2023-11-16 12:23:09 time=2023-11-16T11:23:09.845Z | lvl=DEBUG | corr=1837960c-18c0-4096-b814-3673f25cab12 | trans=1837960c-18c0-4096-b814-3673f25cab12 | op=IoTAgentNGSI.GenericMiddlewares | from=n/a | srv=n/a | subsrv=n/a | msg=Error [MISMATCHED_SERVICE] handling request: The declared service didn't match the stored one in the entity | comp=IoTAgent
```

### PR DESCRIPTION
**Pull request by Madhu1029**
Fixes #1528. Now, uppercase value can also be used for service header in case of update and delete.

### CODE REVIEW

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
Note the merge conflict. It should be easy to solve, just adding the existing and new lines.

**Comment by mapedraza** [comment]
The PR looks good, thank you so much for your contribution. Being said that, I have a couple of comments:
1. it would be great if you could add a test to prove it works propperly. It should prove that creating a group having the FIWARE-service header with capitals can be deleted also using the same FIWARE-service value
2. This fix is valid for group update and delete as `checkServiceIdentity()` function is only used for those 2 methods. What about the rest of the requests? (e.g: group read and list and device CRUDL)

**Comment by Madhu1029** [comment]
> The PR looks good, thank you so much for your contribution. Being said that, I have a couple of comments:
> 
> 1. it would be great if you could add a test to prove it works propperly. It should prove that creating a group having the FIWARE-service header with capitals can be deleted also using the same FIWARE-service value.

I have added test case for deletion and updation with FIWARE-service in uppercase.

> 2. This fix is valid for group update and delete as `checkServiceIdentity()` function is only used for those 2 methods. What about the rest of the requests? (e.g: group read and list and device CRUDL)

As mentioned in issue, the bug exists for deletion and updation only. Group create and read is working fine.

**Comment by Madhu1029** [comment]
Hi @fgalan ,

If the PR seems OK, please merge the PR.

**Pull request merged**
