### PR TITLE
get silently checking duplicates

### PR DESCRIPTION
**Pull request by AlvaroVega**
related https://github.com/telefonicaid/iotagent-node-lib/issues/1007

### CODE REVIEW

**Comment by AlvaroVega** [comment]
there is already a https://github.com/telefonicaid/iotagent-node-lib/blob/667b78ab331aeb8a0564593bcfc214770c361eb7/lib/services/devices/deviceService.js#L228

**Comment by fgalan** [comment]
> Regarding with lint failure there is already a
> 
> https://github.com/telefonicaid/iotagent-node-lib/blob/667b78ab331aeb8a0564593bcfc214770c361eb7/lib/services/devices/deviceService.js#L228

@jason-fox you have more experience in the linter than us. Do you know why the linter raises an error when the disable-next comment is just above that line? For us is quite a mystery... :)

**Comment by jason-fox** [comment]
```
 config.getRegistry().get(deviceObj.id, deviceObj.service, deviceObj.subservice, function (error, device) {
 ```
 
 You are not using `device` in the function below. However it can be useful to leave the full signature since it **may** prove useful should you need to refactor at some point. Better to stop eslint from complaining here.

**Comment by jason-fox** [comment]
If eslint is complaining, then maybe just move the comment closer to the "error"

```javascript
config.getRegistry().get(deviceObj.id, deviceObj.service, 
/* eslint-disable-no-unused-vars */
deviceObj.subservice, function (error, device) {
```

**Comment by fgalan** [comment]
It works. Thanks for the feedback @jason-fox !

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
