### PR TITLE
Including Lazy, Commands, Internal and Static Attributes in payload to IoT Agent Manager

### PR DESCRIPTION
**Pull request by Cerfoglg**
Fix for Issue #768

### CODE REVIEW

**Comment by chicco785** [comment]
@Cerfoglg till test are not fixed, please rename to WIP: ...

**Comment by fgalan** [comment]
We are considering merging PR https://github.com/telefonicaid/iotagent-node-lib/issues/831 and this PR may be impacted (see more details [here](https://github.com/telefonicaid/iotagent-node-lib/issues/830#issuecomment-658222980)). However, any potential conflict is very easy to solve (I understand @jason-fox may provide details, if needed).

Is this PR still active? @Cerfoglg @chicco785 do you agree in merging PR #831 *before* your PR?

**Comment by chicco785** [comment]
sure, let us now when when ready

**Comment by fgalan** [comment]
> sure, let us now when when ready

PR #831 has been merged, so now it's ready :)

The PR would need some adaptation to solve the conflicts. Basically:

1. Solve the conflict accepting your changes
2. Change style with `npm run prettier`

(Please @jason-fox amend mi if I'm wrong)

**Comment by chicco785** [comment]
it looks like some already introduced support for commands and static attributes, thus this pr actually adds only lazy and internal_attributes.

**Comment by chicco785** [comment]
@fgalan this should ready for landing now

**Comment by chicco785** [comment]
any chance to merge this PR?

**Comment by fgalan** [comment]
> any chance to merge this PR?

A small conflict on CNR files has arisen after merging your other PR ;)

We have some "sensitive" PRs queued (in the sense they could have impact in e2e behaviors). We are trying to have a full CI e2e pass after merging one PR and before merging the next PR. The CI e2e takes a long time and is executed typically by night, so we are progressing slowly.

Be patient, pls... I think that sooner than later this PR will be the next one in queue :)

**Comment by chicco785** [comment]
> > any chance to merge this PR?
> 
> A small conflict on CNR files has arisen after merging your other PR ;)
fixed by https://github.com/telefonicaid/iotagent-node-lib/pull/793/commits/64563fb47b6bff3a5fb3699e70b6814454676a05

> 
> We have some "sensitive" PRs queued (in the sense they could have impact in e2e behaviors). We are trying to have a full CI e2e pass after merging one PR and before merging the next PR. The CI e2e takes a long time and is executed typically by night, so we are progressing slowly.
> 
> Be patient, pls... I think that sooner than later this PR will be the next one in queue :)

sure!

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
