### PR TITLE
Add Null expression tests

### PR DESCRIPTION
**Pull request by mapedraza**
https://github.com/telefonicaid/iotagent-node-lib/issues/1440#issuecomment-1736983813

When posting a measure `v` with value `Null` to a group with the following attributes:

**Expression**
```js
            active: [
                {
                    name: 'a',
                    type: 'Number',
                    expression: 'v'
                },
                {
                    name: 'b',
                    type: 'Number',
                    expression: 'v*3'
                },
                {
                    name: 'c',
                    type: 'Boolean',
                    expression: 'v==null'
                },
                {
                    name: 'd',
                    type: 'Text',
                    expression: "v?'no soy null':'soy null'"
                },
                {
                    name: 'e',
                    type: 'Text',
                    expression: "v==null?'soy null':'no soy null'"
                },
                {
                    name: 'f',
                    type: 'Text',
                    expression: "(v*3)==null?'soy null':'no soy null'"
                },
                {
                    name: 'g',
                    type: 'Boolean',
                    expression: 'v == undefined'
                }
            ]
```

**Expectations**
```js
                    v: {
                        value: null,
                        type: 'Number'
                    },
                    b: {
                        value: 0,
                        type: 'Number'
                    },
                    c: {
                        value: true,
                        type: 'Boolean'
                    },
                    d: {
                        value: 'soy null',
                        type: 'Text'
                    },
                    e: {
                        value: 'soy null',
                        type: 'Text'
                    },
                    f: {
                        value: 'no soy null',
                        type: 'Text'
                    },
                    g: {
                        value: true,
                        type: 'Boolean'
                    }
```

### CODE REVIEW

**Comment by mapedraza** [comment]
Pending to validate if expectations are the expected

**Comment by mapedraza** [comment]
Added more cases after discussing with @mrutid and some other minor fixes
- With null values
- With null and skipValues 
- Without values (NaN)
- Without values (NaN) and skipValues
- With explicitAttrs

**Comment by mapedraza** [comment]
Conclusions:

- case `b` (`v*3`)
   - For Null values, is always failing (treating `Null` as 0)
   - For NaN values, it works well, giving Null as response. 
- case `f` (`(v*3)==Null?'soy null':'no soy null'`) is always failing
- Using `explicitAttrs` acts as sending a measurement with null value

**Comment by AlvaroVega** [comment]
> Conclusions:
> 
>     * case `b` (`v*3`)
>       
>       * For Null values, is always failing (treating `Null` as 0)
>       * For NaN values, it works well, giving Null as response.
> 
>     * case `f` (`(v*3)==Null?'soy null':'no soy null'`) is always failing
> 
>     * Using `explicitAttrs` acts as sending a measurement with null value

Then these tests should fails in that expected values? Currently are passing.

**Comment by mapedraza** [comment]
> > * For Null values, is always failing (treating `Null` as 0)
> > * case `f` (`(v*3)==Null?'soy null':'no soy null'`) is always failing
> 
> Then these tests should fails in that expected values? Currently are passing. I mean these tests should check expected values in each case.

Right now, tests are set with the real behaviour. This need to be fixed according the real expected value in a subsequent PR

**Comment by mapedraza** [comment]
overpassed by https://github.com/telefonicaid/iotagent-node-lib/pull/1474

**Pull request closed without merging**
