### PR TITLE
Add Node v18 to CI test

### PR DESCRIPTION
**Pull request by mapedraza**
This PR adds Node v18 to the CI unit tests

### CODE REVIEW

**Comment by mapedraza** [comment]
Should Lint steps need to be updated to a newer version?. I.E:
https://github.com/telefonicaid/iotagent-node-lib/blob/1e89c6728652e37e202c47facc8d16d04593a7bd/.github/workflows/ci.yml#L17

https://github.com/telefonicaid/iotagent-node-lib/blob/1e89c6728652e37e202c47facc8d16d04593a7bd/.github/workflows/ci.yml#L37

**Comment by fgalan** [comment]
> Should Lint steps need to be updated to a newer version?. I.E:
> 
> https://github.com/telefonicaid/iotagent-node-lib/blob/1e89c6728652e37e202c47facc8d16d04593a7bd/.github/workflows/ci.yml#L17
> 
> https://github.com/telefonicaid/iotagent-node-lib/blob/1e89c6728652e37e202c47facc8d16d04593a7bd/.github/workflows/ci.yml#L37

It seems to be a good idea. The newest possible.

**Comment by fgalan** [comment]
I have merged master into this PR in commit [220058a](https://github.com/telefonicaid/iotagent-node-lib/pull/1242/commits/220058a42a3c65b3a0b87bbb3b624e33380b4c81) to incorporate the changes in PR https://github.com/telefonicaid/iotagent-node-lib/pull/1250 (MongoDB driver migration to 4.x) to check if they could solve the Node v18 tests, but it seems the issue persists :(

**Comment by AlvaroVega** [comment]
Maybe we can close this PR due to https://github.com/telefonicaid/iotagent-node-lib/pull/1333

**Comment by mapedraza** [comment]
As noted by @AlvaroVega, closed due to #1333

**Pull request closed without merging**
