### PR TITLE
fix callback when deleting a not existing device

### LINKED ISSUE #585: if context broker cannot be reached device is not provisioned
i have done only basic tests, but basically, the process of device provisioning freezes until timeout is reached, and the device is not registered.

response should be faster probably. options could be:
* reduce time out so to immediately return error message to user.
* insert contextBroker provisioning in a queue, that when connectivity is restored is actually emptied

### PR DESCRIPTION
**Pull request by chicco785**
if device to be deleted is not found, immediately return 404.
fix https://github.com/telefonicaid/iotagent-ul/issues/249 & #587

### CODE REVIEW

**Comment by chicco785** [comment]
resolved conflicts on the history of change via commit #eeb5a69

**Comment by dcalvoalonso** [comment]
Only one very minor comment: please run grunt lint and fix the reported errors:

```
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:lib" (jshint) task

   lib/commonConfig.js
     98 |        config.contextBroker.url = "http://" + process.env.IOTA_CB_HOST;
                                                     ^ Strings must use singlequote.
    100 |            config.contextBroker.url += ":" + process.env.IOTA_CB_PORT;
                                                    ^ Strings must use singlequote.
    141 |        config.iotManager.url = "http://" + process.env.IOTA_IOTAM_HOST;
                                                  ^ Strings must use singlequote.
    143 |            config.iotManager.url += ":" + process.env.IOTA_IOTAM_PORT;
                                                 ^ Strings must use singlequote.
   lib/fiware-iotagent-lib.js
     87 |            newConfig.contextBroker.url = "http://" + newConfig.contextBroker.host + ":" + newConfig.contextBroker.port;
                                                            ^ Strings must use singlequote.
     87 |            newConfig.contextBroker.url = "http://" + newConfig.contextBroker.host + ":" + newConfig.contextBroker.port;
                                                                                                 ^ Strings must use singlequote.
     89 |            newConfig.contextBroker.url = "http://" + newConfig.contextBroker.host;
                                                            ^ Strings must use singlequote.
     95 |            newConfig.iotManager.url = "http://" + newConfig.iotManager.host + ":" + newConfig.iotManager.port;
                                                         ^ Strings must use singlequote.
     95 |            newConfig.iotManager.url = "http://" + newConfig.iotManager.host + ":" + newConfig.iotManager.port;
                                                                                           ^ Strings must use singlequote.
     97 |            newConfig.iotManager.url = "http://" + newConfig.iotManager.host;
                                                         ^ Strings must use singlequote.
   lib/services/ngsi/subscriptionService.js
    199 |    if (device.cbHost && device.cbHost.indexOf("://") !== -1) {
                                                             ^ Strings must use singlequote.
    201 |    } else if (device.cbHost && device.cbHost.indexOf("://") == -1) {
                                                                    ^ Strings must use singlequote.
    201 |    } else if (device.cbHost && device.cbHost.indexOf("://") == -1) {
                                                                        ^ Expected '===' and instead saw '=='.
    202 |        options.uri = "http://" + device.cbHost + '/v1/unsubscribeContext';
                                        ^ Strings must use singlequote.
   lib/services/northBound/deviceProvisioningServer.js
    236 |                } else if (error && error.code == 404) {
                                                          ^ Expected '===' and instead saw '=='.

>> 15 errors in 44 files

```

Not all of them are related to this specific PR but to https://github.com/telefonicaid/iotagent-node-lib/pull/584.

**Comment by chicco785** [comment]
my bad for the linting what's the best way? should i make a new PR to fix them in relation to the merged code?

**Comment by fgalan** [comment]
Clearner way is in a new PR (then update the present one once it gest master).

**Comment by chicco785** [comment]
#602 fix linting issues for #584 

i would suggest to proceed as follows:
1. merge #602 
1. rebase this
1. lint this pr
1. merge this pr

**Comment by chicco785** [comment]
#issuecomment-378328595 fixed by b1b0819

**Comment by fgalan** [comment]
Step 1 completed. If steps 2 and 3 are also completed, then we can merge, after @dcalvoalonso LGTM.

**Comment by chicco785** [comment]
@fgalan @dcalvoalonso i can confirm that steps 2 and 3 have been completed

**Comment by dcalvoalonso** [comment]
LTGM! Thanks!!

**Pull request merged**
