### PR TITLE
Add tests using explicitAttrs with value `[ ]`

### PR DESCRIPTION
**Pull request by mapedraza**
Adding tests described in #1600 

- 0531 - Group with explicit attrs:[ ] (empty array) + active attributes + static attributes
   - A - WHEN sending both provisioned and not object_ids (measures) through http IT should NOT store anything into the Context Broker (No request to CB)
- 0532 - Group with explicit attrs:[ ] (empty array) + active attributes + static attributes + timestamp:true
   - A - WHEN sending both provisioned and not object_ids (measures) through http IT should NOT store anything into the Context Broker (No request to CB)
   - B - WHEN sending data and a measure called TimeInstant through http IT should NOT store anything into the Context Broker (No request to CB)
- 0533 - Group with explicit attrs:[ ] (empty array) + active attributes + TimeInstant attribute + static attributes + timestamp:true
   - A - WHEN sending data and a measure called "t" (defined as TimeInstant attribte) through http IT should NOT store anything into the Context Broker (No request to CB)
   - B - WHEN sending data and a measure called TimeInstant through http IT should NOT store anything into the Context Broker (No request to CB)

BUT some problems were discovered when using TimeInstant attribute and fucntionalities in cases 533 A) and B):

**0533 B**
``` diff
Assertion Error - Context Broker received payload differs from expectation
+ expected - actual

-{
-  "TimeInstant": {
-    "type": "DateTime"
-    "value": "2015-12-14T08:06:01.468Z"
-  }
-  "id": "TestType:TestDevice"
-  "type": "TestType"
-}
+{}
```

**0533 B**
``` diff
Assertion Error - Context Broker received payload differs from expectation
+ expected - actual

-{
-  "DateIssued": {
-    "metadata": {
-      "TimeInstant": {
-        "type": "DateTime"
-        "value": "2024-04-29T16:07:27.281Z"
-      }
-    }
-    "type": "DateTime"
-    "value": "2015-12-14T08:06:01.468Z"
-  }
-  "TimeInstant": {
-    "type": "DateTime"
-    "value": "2024-04-29T16:07:27.281Z"
-  }
-  "id": "TestType:TestDevice"
-  "type": "TestType"
-}
+{}
```

### CODE REVIEW

**Comment by mapedraza** [comment]
As discussed, this PR should be divided in 2

**Comment by fgalan** [comment]
> As discussed, this PR should be divided in 2

One of then with working tests 0531 and 0532, to be merged (closing #1600) and other PR with 0533 to be on hold as a regression tests for issue #1606

**Comment by AlvaroVega** [comment]
These tests are related with PR https://github.com/telefonicaid/iotagent-node-lib/pull/1593 and described as 
- Fix: TimeInstant mapped from attribute overrides default behaviours (#1557)

So not sure if a measure mapped to TimeInstnat attribute should not be propagated to CB in this case.

**Comment by mapedraza** [comment]
> * behaviours

As my understanding, TimeInstant should work as any other attribute, so, it should be filtered by explicitAttrs like any other attribute.

**Comment by mapedraza** [comment]
> c742681

Tests 533 removed here:
https://github.com/telefonicaid/iotagent-node-lib/pull/1605/commits/c7426811b164631d200d48372527b783ced77e78

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
