### PR TITLE
[WIP] Updates dependencies while supporting Node.js v4

### PR DESCRIPTION
**Pull request by dcalvoalonso**

### CODE REVIEW

**Comment by fgalan** [comment]
Has been this PR overpassed by https://github.com/telefonicaid/iotagent-node-lib/pull/682? Should be closed?

**Comment by dcalvoalonso** [comment]
Yes, it can be closed.

**Comment by AlvaroVega** [comment]
After this PR we are obtained the following error in using a iotagent with a replicaset:
```
time=2018-11-05T10:06:44.892Z | lvl=INFO | corr=4406f544-3f93-4bb9-999f-2bedff620ae9 | trans=4406f544-3f93-4bb9-999f-2bedff620ae9 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 1 | comp=IoTAgent
(node:22285) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
time=2018-11-05T10:06:45.029Z | lvl=ERROR | corr=4406f544-3f93-4bb9-999f-2bedff620ae9 | trans=4406f544-3f93-4bb9-999f-2bedff620ae9 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name | comp=IoTAgent
```

**Comment by fgalan** [comment]
We have detected this in the CI e2e envoriment, which uses a replica set. It seems that PR https://github.com/telefonicaid/iotagent-node-lib/pull/695 fixes it.

Please, @dcalvoalonso take this into account if new updates of the mongodb / mongoose (not sure which one is causing the issue) are done in agents repo t (although probably agents are not using MongoDB directly, but through the library).

**Comment by dcalvoalonso** [comment]
Ok @fgalan! I take note of this! ;)

**Pull request closed without merging**
