### PR TITLE
Use trust and cbHost from deviceGroup in typeInformation

### PR DESCRIPTION
**Pull request by AlvaroVega**
related manager fix https://github.com/telefonicaid/iotagent-manager/pull/158

related issue https://github.com/telefonicaid/iotagent-node-lib/issues/685

### CODE REVIEW

**Comment by dcalvoalonso** [comment]
Initially the PR is OK for me. I am just thinking if it would be appropriate to include some NGSIv2 test to validate the fix since @chicco785 reported in https://github.com/telefonicaid/iotagent-node-lib/issues/685 that createInitialEntityNgsi2 was one of the functions implied.

**Comment by AlvaroVega** [comment]
Some tests were also updated:
- https://github.com/telefonicaid/iotagent-node-lib/pull/697/files#diff-ac8b21ced402dd381fc2421d96b32550
- https://github.com/telefonicaid/iotagent-node-lib/pull/697/files#diff-cbff613fd2ae9320460915f3973b1a84

**Comment by dcalvoalonso** [comment]
Actually, the two modified tests are related to NGSIv1 and used in https://github.com/telefonicaid/iotagent-node-lib/blob/master/test/unit/general/iotam-autoregistration-test.js.
For that reason and as the issue reported by @chicco785 refers specifically to `createInitialEntityNgsi2`, I was thinking that it may be appropriate to create similar tests for NGSIv2.

**Comment by dcalvoalonso** [comment]
Thanks @AlvaroVega ! LGTM!

**Comment by fgalan** [comment]
After @dcalvoalonso I'm merging for not delaying the PR much more. Of course feedback from @chicco785 can be taken into account (in a next PR) if at the end is provided.

**Pull request merged**
