### PR TITLE
Fix for a problem with active attribute updates coming from Context Broker

### PR DESCRIPTION
**Pull request by marcinbudny**
1) The IoT agent crashes when active attribute update arrives from Context Broker and `commands` property of the entity type is not defined. Problem lays in `contextServer.executeUpdateSideEffects` not checking if the `commands` property is defined.
2) Once that was fixed, it turned out wrong attributes were passed to client handler. In `contextServer.generateUpdateActions` they were taken from `device` instead of `contextElement`.

This is a corrected version of telefonicaid/iotagent-node-lib#96 pull request that was targeting a wrong branch. This one targets develop. Since the pull request is from master branch of a fork, some additional commits are listed in it. I hope this will not be a problem. 

Also some syntax/style issues have been fixed.

### CODE REVIEW

**Comment by dmoranj** [comment]
The additional commit should not be a problem, they seem to be just the release version commits. It looks good to me. Just a last detail, please add a line in the CHANGES_NEXT_RELEASE describing the bug, for the release changelog.

**Comment by marcinbudny** [comment]
I update the file, however I can see that it's contents on the develop branch have changed significantly. I'm not sure if this will merge gracefully.

**Comment by dmoranj** [comment]
It seems to me the creation from the `master` branch was more problematic than it seemed to at first. I think the best will be to create a new branch from develop and cherry pick your commits into it. I can do that to save yo from creating yet another one PR.

**Comment by marcinbudny** [comment]
OK, that will be great.

**Comment by dmoranj** [comment]
Created PR #100 with your changes. Check it out to see if it's ok, and we will merge it.

**Comment by dmoranj** [comment]
I'm closing this PR, as it's a duplicate now.

**Pull request closed without merging**
