### PR TITLE
Allow to send to CB batch update for multimeasures for NGSI-LD

### PR DESCRIPTION
**Pull request by jason-fox**
Equivalent of #1607 - it is just a copy of `sendUpdateValueNgsi2()` for now with relevant changes for NGSI-LD.

At some point the v2 functionality had been updated to : `Not update value in the Context Broker  with an empty payload`.
This path is more frequent in NGSI-LD as attributes which resolve to `null` are already removed. This leads to the update of a large number of test expectations where an "empty entity" was being appended to the upsert.

Several (mainly JEXL) tests are no longer relevant, since they result in a `null` and no CB update - I have currently set those tests to PENDING for now pending further review - I can delete them if necessary.

### CODE REVIEW

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
An entry in CHANGES_NEXT_RELEASE describing the change in this PR (including issue reference, if any) would be great.

**Comment by jason-fox** [comment]
> I think it would be better to delete them, for cleanness, please.

Fixed  079bb44

> An entry in CHANGES_NEXT_RELEASE

Fixed 8de86c7

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
