### PR TITLE
[WIP] "configGroups" literal in configuration group operations URL (old PR #780)

### PR DESCRIPTION
**Pull request by fgalan**
Issue #752 

This is a port of old PR #780 (authored by @Jagatjot). That PR was closed by the author but in order to not losing his valuable work, we are opening this one. If somebody is interested in continuing his work, just tell me.

Please have a look at unresolved comments in the original PR.

### CODE REVIEW

**Comment by fgalan** [comment]
Note old PR has diff values of +1,624 -13 while this one (at the moment of the first commit, just after porting) has +1,621 −12. The +3 -1 difference is due to a "cleaner" CHANGES_NEXT_RELEASE addition in this PR.

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,

I have started working on this PR.

Thanks!

**Comment by fgalan** [comment]
> 
> 
> Hi @fgalan ,
> 
> I have started working on this PR.
> 
> Thanks!

Great to know! :)

I see two options:

1. Take the content of this PR (https://patch-diff.githubusercontent.com/raw/telefonicaid/iotagent-node-lib/pull/922.diff) to create one of yours and continue the work from it. In that case, this PR #922 would be closed at the end.
2. Do a PR to complete this one, using feature/752_cgroup_names as base branch. Once that PR gets merged, this one (PR #922) would be merge with the whole work.

As you prefer... :)

**Comment by fgalan** [comment]
(Self-note)

The PR would need some adaptation to solve the conflicts. Basically:

1. Solve the conflict accepting your changes
2. Change style with `npm run prettier`

(Please @jason-fox amend mi if I'm wrong)

**Comment by fgalan** [comment]
> The PR would need some adaptation to solve the conflicts.

Done in c9b00ef (prettier) and a1bf53f (lint).

Before using them, I thought that the prettier target was the one modifying the code to fit the style and the lint target was the one to check that the style was one (but without modifying the code). However, both modify the code. Interesting...

**Comment by Madhu-NEC** [comment]
Hi @fgalan,

>1. Take the content of this PR (https://patch-diff.githubusercontent.com/raw/telefonicaid/iotagent-node-lib/pull/922.diff) to create one of yours and continue the work from it. In that case, this PR #922 would be closed at the end.

I am planning to use the first option as mentioned above.

>The PR would need some adaptation to solve the conflicts.

As per my understanding, to change the style of the code in my new PR, I only need to run `npm run prettier`. Please confirm.

**Comment by fgalan** [comment]
> As per my understanding, to change the style of the code in my new PR, I only need to run `npm run prettier`. Please confirm.

I think so, but @jason-fox knows that better than me and can provide better feedback :) Maybe `npm run lint` is also required.

**Comment by Madhu-NEC** [comment]
Hi @fgalan , @jason-fox 
I have created the new [PR#954](https://github.com/telefonicaid/iotagent-node-lib/pull/954) corresponding to this PR as discussed.

**Comment by fgalan** [comment]
> 
> 
> Hi @fgalan , @jason-fox
> I have created the new [PR#954](https://github.com/telefonicaid/iotagent-node-lib/pull/954) corresponding to this PR as discussed.

Great! So I think I can close now this PR so we continue in PR #954

**Pull request closed without merging**
