### PR TITLE
Task/not loose invalid id type in measures

### PR DESCRIPTION
**Pull request by AlvaroVega**
related https://github.com/telefonicaid/iotagent-json/pull/804

### CODE REVIEW

**Review by mrutid — APPROVED** [review]
LGTM

**Review by mrutid — APPROVED** [review]
LGTM

**Comment by AlvaroVega** [comment]
FIXME: we need to document this

**Comment by AlvaroVega** [comment]
Tested with: 
````
curl -i -X POST 'http://localhost:7897/iot/json?i=disp5&k=k48pobwrxusoree1xchcnqqfg' -d '{ "id":"665190-5", "type": "piedra", "level": "33", "internalId": "665190-1-1"}' -H 'content-type: application/json'
```

**Pull request merged**
