### PR TITLE
fix multientity jexl and static test: replace static -> staticAttributes

### PR DESCRIPTION
**Pull request by AlvaroVega**

### CODE REVIEW

**Comment by mapedraza** [comment]
This provision is using `static` instead of `staticAttributes` in the same test file:
https://github.com/telefonicaid/iotagent-node-lib/blob/c6bba3d9c634ae172fade41a986e20659f7e2fd0/test/unit/ngsiv2/plugins/multientity-plugin_test.js#L544-L575

This means the test using type GPS2:
https://github.com/telefonicaid/iotagent-node-lib/blob/c6bba3d9c634ae172fade41a986e20659f7e2fd0/test/unit/ngsiv2/plugins/multientity-plugin_test.js#L1319-L1350

Is also having an expectation without static attrs:
https://github.com/telefonicaid/iotagent-node-lib/blob/c6bba3d9c634ae172fade41a986e20659f7e2fd0/test/unit/ngsiv2/examples/contextRequests/updateContextMultientityPlugin16.json#L1-L25

**Comment by mapedraza** [comment]
Also test `test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js` use `static` instead of `staticAttributes` on types:
- GPS3
- GPS4
- GPS5
- GPS5b
- GPS6
- GPS7

**Comment by AlvaroVega** [comment]
> Also test `test/unit/ngsiv2/expressions/jexlBasedTransformations-test.js` use `static` instead of `staticAttributes` on types:
> 
>     * GPS3
> 
>     * GPS4
> 
>     * GPS5
> 
>     * GPS5b
> 
>     * GPS6
> 
>     * GPS7

Done in https://github.com/telefonicaid/iotagent-node-lib/pull/1499/commits/e3645e6d5b5a00e5781eacbe2b2cd645b871adca

**Review by mapedraza — APPROVED** [review]
LGTM

**Review by mapedraza — COMMENTED** [review]
It is weird there are no changes required in NGSI request expectations after fixing the static attributes definition on groups.

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
