### PR TITLE
#671 issue

### PR DESCRIPTION
**Pull request by gabrieledeluca**
This solve Payload for device provisioning #671 issue using no pattern validation for object_id field in create e update device payload @fgalan :-)

### CODE REVIEW

**Comment by gabrieledeluca** [comment]
committed also #675

**Comment by fgalan** [comment]
With regards to #675 please find my feedback in the issue itself: https://github.com/telefonicaid/iotagent-node-lib/issues/675#issuecomment-426228935

With regards to #671 note that sometimes object_id is directly used for the attribute name. In particular, when no matching mapping (prevously defined in the provisioning operation used to created the devide) is found, then object_id is used. 

This PR relaxes the checking in two places (createDevice.json and updateDevice.json). Both cases apply only to the provision API (in which case it would be ok)? Is IOTAgent ensuring that for these object_ids without mapping no forbidden char is progresin in the name towards CB?

**Comment by fgalan** [comment]
Any update on this PR @gabrieledeluca , please?

Just to know... :)

**Comment by gabrieledeluca** [comment]
Hello @fgalan, nothing from my side: regarding the #671, I provided some examples in the OPC UA domain so I needed to relax the validation on the object_id field (the PR passed tests but I didn't write unit tests to check the potential forwarding of OCB forbidden characters). Instead regarding #675 I agree with you about backward compatibility although null value is semantically better.

**Comment by jason-fox** [comment]
@gabrieledeluca - has this been superseded by. #920 ?

**Pull request closed without merging**
