### PR TITLE
Review the whole documentation in order to remove deprecated / removed features

### PR DESCRIPTION
**Pull request by mapedraza**
Issue #1329

- [x] References to "plugin" (and its variant "plug-in") https://github.com/telefonicaid/iotagent-node-lib/pull/1437/commits/10aa0b41326074a7d494e25f1514cfa1eb736658
- [x] References to "bidirectional" (deprecated feature) - No references found
- [x] References to "appendMode" and "IOTA_APPEND_MODE" (and its variants "append" and "APPEND") (deprecated feature) https://github.com/telefonicaid/iotagent-node-lib/pull/1437/commits/7b50a965af6d965013c80be7421531cea9b8cac3
- [x] References to "legacy" and " expressionLanguage" (legacy expressions) https://github.com/telefonicaid/iotagent-node-lib/pull/1437/commits/eea68d83deaf855b8a3024c110a84df6dd1c2be8

### CODE REVIEW

**Comment by mapedraza** [comment]
Remaining plugin references:

https://www.github.com/telefonicaid/iotagent-node-lib/blob/task/doc-rework-removed-deprecated/doc/admin.md#L327-L329

**Comment by mapedraza** [comment]
> Remaining plugin references:
> 
> https://www.github.com/telefonicaid/iotagent-node-lib/blob/task/doc-rework-removed-deprecated/doc/admin.md#L327-L329

This should be clarified in further steps

NTC

**Comment by mapedraza** [comment]
This PR is ready to review

**Review by fgalan — APPROVED** [review]
LGTM

**Pull request merged**
