### PR TITLE
Added "cgroups" literal in configuration group operations URL

### PR DESCRIPTION
**Pull request by Jagatjot**
Fixes Issue #752

### CODE REVIEW

**Comment by fgalan** [comment]
Could you rebase/squash your PR to join all the commits, pls? 35 commits (by the time being) is pretty "noisy"...

**Comment by Jagatjot** [comment]
@fgalan  I have rasied a PR with a rebase of commits as https://github.com/telefonicaid/iotagent-node-lib/pull/780. The test coverage is still decreasing by 0.0.7%.

**Comment by fgalan** [comment]
I understand this is an old version of current #780. In that case, plase @Jagatjot close this PR, so we can only one. Thanks!

**Comment by Jagatjot** [comment]
> I understand this is an old version of current #780. In that case, plase @Jagatjot close this PR, so we can only one. Thanks!

Thank you @fgalan . I am closing this one so you can have a look at https://github.com/telefonicaid/iotagent-node-lib/pull/780.

**Pull request closed without merging**
